### PR TITLE
Issue #4 develop register

### PR DESCRIPTION
**Pull request by ebebbington**
What's developed:

* Register view, stylesheet and JS
* Updated the header and the sidebar so i could actually get some markup for the register view done (though the design is in the early stages)
* Routes for GET and POST on /register, that will validate the creds and insert into the db
* Users db table is completely done to support registration

What isn't implemented:

* Hashing for passwords (no modules that i know of can do this and compare passwords)
* Vue - had too much trouble trying to build all the client stuff from scratch with very limited knowledge, which brang a halt to everything so i decided to use the basics for the time being. I can create a new issue for someone to pick up to convert the client side stuff into Vue

Questions:

* On a POST request where the validation failed, would using something other than a 200 status and `success: false` be better?
* Is it worth to send the status codes in the JSON response?

### CODE REVIEW

**Comment by ebebbington** [comment]
Also meets #6, the `prepare` method will populate placeholders in base queries with data

**Comment by ebebbington** [comment]
Created an issue for hashing passwords #15

**Comment by Guergeiro** [comment]
Front end stuff is not my forte 😅

From what I can see, everything seems fine (just don't like the use of jQuery). Could you point me out what steps you take to run the app? That way I can test it in my system.

**Comment by ebebbington** [comment]
> Front end stuff is not my forte 😅
> 
> From what I can see, everything seems fine (just don't like the use of jQuery). Could you point me out what steps you take to run the app? That way I can test it in my system.

Sure, there's a bit in the README but i could probably explain more:

```
$ docker-compose up # wait for drash to start
# go to http://localhost:1667/register
```

**Comment by ebebbington** [comment]
> Everything is working in my end. #15 can now be address with that module we talked about.
> Looks good.
> 
> I think @crookse needs to approve because he is following this more than I am.

He's pretty much left this down to me but i will definitely want to utilise his frontend knowledge when it comes to the UI/Vue stuff :P

Gonna merge now, also means i can get to work on the other issues

**Pull request merged**
